### ISSUE TITLE
error: no matching package named `anvil` found

### ISSUE THREAD

**Issue by ildefons** [solidquant/evm-tracing-samples#1]
error: no matching package named `anvil` found
location searched: https://github.com/foundry-rs/foundry.git#d93312bf
required by package `revm-playground v0.1.0 (/home/ildefons/mevprj/evm-tracing-samples/rust)`

**Comment by ildefons** [comment]
Solved by upgrading rustc

**Comment by solidquant** [comment]
Hey, I just checked the issue. Sounds good that your problem was resolved.

The current version of Foundry/Anvil seem to work with the newest version of Rust.

I've checked mine and it was: rustc 1.71.0 (8ede3aae2 2023-07-12)
